Added spanish translation
eurofurence/ef-app_react-native pull request #130
Opened 2023-09-17 12:42 UTC by tekofx

2023-10-03 12:32 UTC, docimin requested changes
Some english translations here, would recommend changing these too.

2023-10-14 09:37 UTC, tekofx commented
Ok, I think everything is translated now

2023-10-25 22:58 UTC, docimin approved these changes

2024-08-25 13:32 UTC, Requinard commented
Hey, if you are still interested in adding a spanish translation you should try fixing it with the latest few commits. We'll take a look if you do!

2025-08-09 12:08 UTC, lukashaertel commented
This is sadly a little out of date to merge with the updates. But thank you for your effort, we'll see about sanitizing the translations at some time, maybe then it'll be nice to add a Spanish translation again.

2025-08-09 12:08 UTC, closed without merging