refactor(eslint): move to newer flatconfig
eurofurence/ef-app_react-native pull request #151
Opened 2024-09-02 18:57 UTC by Requinard

yeah see the latest commit for the real message.

bumps eslint stuff and adds new rules

2024-09-02 19:15 UTC, lukashaertel requested changes

2024-09-02 19:15 UTC, lukashaertel commented on src/testUtils.tsx
> +    // @ts-expect-error This type somehow does not match
Marked as ` error TS2578: Unused '@ts-expect-error' directive.`

2024-09-02 19:35 UTC, Fenrikur commented
Since you are not adhering to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), please squash merge this branch once review is done and changes have been approved. (=
I've altered the PR title to conform with Conventional Commits accordingly.

2024-09-02 19:46 UTC, Fenrikur commented on .github/workflows/nodejs.yml
Would suggest turning
```yaml
on:
  push:
    branches: [ "*" ]
```

into just
```yaml
on:
  push:
```
so the workflow runs on every push.

2024-09-02 19:47 UTC, Fenrikur commented on .github/workflows/nodejs.yml
>            cache: 'npm'
Since we're using `pnpm`, might be worth looking into using the appropriate cache setting? (:
```yaml
cache: 'pnpm'
```

2024-09-03 16:45 UTC, lukashaertel approved these changes

2024-09-03 16:57 UTC, merged